[tools]
"rust" = { version = "1.95", profile = "default" }
"github:rhysd/actionlint" = "1"

[tasks.fmt-lint-test-build]
run = [
    "cargo fmt",
    "cargo clippy -- -D warnings",
    "actionlint",
    "cargo test",
    "cargo build --release",
]

[tasks.ci]
run = [
    "cargo fmt -- --check",
    "cargo clippy -- -D warnings",
    "actionlint",
    "cargo test",
    "cargo build --release",
]
