[tools]
"rust" = { version = "1.95", components = "rustfmt,clippy" }
"github:rhysd/actionlint" = "1.7.12"
"github:koalaman/shellcheck" = "0.11.0"
"github:crate-ci/cargo-release" = "1.1.2"
"github:convco/convco" = "0.6.4"
"deno" = "2.8.0"
yq = "latest"

[tasks.all-local]
run = [
    "cargo fmt",
    "convco check 93da8491..HEAD",
    "cargo clippy -- -D warnings",
    "actionlint",
    "cargo test",
    "cargo build --release",
    "cd e2e-tests && deno fmt",
    "cd e2e-tests && deno lint",
    "cd e2e-tests && ./run-docker.sh",
    "echo \"version: $(convco version --bump) ($(convco version --bump --label))\"",
]

[tasks.run-e2e-variations]
run = [
    "cd e2e-tests && ./run.sh",
    "cd e2e-tests && ./run-docker.sh",
    "cd e2e-tests && CFG_SYNC=target/releas/cfgsync ./run.sh",
    "cd e2e-tests && CFG_SYNC=target/releas/cfgsync ./run-docker.sh",
]

[tasks.ci-check]
run = [
    "cd e2e-tests && deno fmt",
    "cd e2e-tests && deno lint",
    "cargo fmt -- --check",
    "cargo clippy -- -D warnings",
    "actionlint",
    "cargo test",
]
