[[sync]]
source = "./source"
target = "./target"
owner = "root:root"
permissions = "644"
globs = [
    "*.conf",
    { pattern = "override-perms.key", permissions = "600" },
    { pattern = "override-owner.key", permissions = "644", owner = "nobody:nogroup" },
]
