name: Release

on:
  workflow_call:
    inputs:
      git_ref:
        required: true
        type: string
      run_e2e_tests:
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            primary: x86_64-unknown-linux-gnu
            cross_compile: aarch64-unknown-linux-gnu
            linux_cross_compile_deps: true
            e2e_test_command: "./e2e-tests/run-docker.sh"
          - os: macos-latest
            primary: aarch64-apple-darwin
            cross_compile: x86_64-apple-darwin
            linux_cross_compile_deps: false
            e2e_test_command: "./e2e-tests/run.sh"
    runs-on: ${{ matrix.os }}
    env:
      PRIMARY: ${{ matrix.primary }}
      CROSS_COMPILE: ${{ matrix.cross_compile }}
      E2E_TEST_COMMAND: ${{ matrix.e2e_test_command }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_ref }}
      - uses: ./.github/actions/setup
        with:
          linux-cross-compile-deps: ${{ matrix.linux_cross_compile_deps }}
      - run: rustup target add "${PRIMARY}" "${CROSS_COMPILE}"
      - run: cargo build --release --target "${PRIMARY}"
      - run: CFGSYNC="target/${PRIMARY}/release/cfgsync" "${E2E_TEST_COMMAND}"
        if: inputs.run_e2e_tests
      - run: tar -czf "cfgsync-${PRIMARY}.tar.gz" -C "target/${PRIMARY}/release" cfgsync
      - run: cargo build --release --target "${CROSS_COMPILE}"
      - run: tar -czf "cfgsync-${CROSS_COMPILE}.tar.gz" -C "target/${CROSS_COMPILE}/release" cfgsync
      - uses: actions/upload-artifact@v4
        with:
          name: cfgsync-${{ matrix.primary }}
          path: cfgsync-${{ matrix.primary }}.tar.gz
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: cfgsync-${{ matrix.cross_compile }}
          path: cfgsync-${{ matrix.cross_compile }}.tar.gz
          if-no-files-found: error

