name: Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      git-ref: ${{ inputs.tag }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: Generate checksums
        run: shasum -a 256 cfgsync-*/*.tar.gz > checksums.txt

      - name: Attest artifacts
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            cfgsync-*/*.tar.gz
            checksums.txt

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          files: |
            cfgsync-*/*.tar.gz
            checksums.txt
          generate_release_notes: true
