name: Bump version and tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  check:
    if: "!startsWith(github.event.head_commit.message, 'chore: Release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - uses: Swatinem/rust-cache@v2

      - run: mise run ci

  bump:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: jdx/mise-action@v2

      - uses: Swatinem/rust-cache@v2

      - name: Release
        run: |
          LEVEL=$(convco version --bump --label)
          if [ -z "$LEVEL" ]; then
            echo "No bump needed. Skipping."
            exit 0
          fi
          echo "Bump level: $LEVEL"
          cargo release "$LEVEL" --no-publish --no-confirm --execute
