name: PR

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - run: mise run ci-check

  build:
    uses: ./.github/workflows/_build.yml
    with:
      git_ref: ${{ github.head_ref }}
      run_e2e_tests: true
